name: Docs Pipeline

on:
  push:
    branches: [main]
    paths:
      - "hardware/**"
      - "docs/**"
      - "scripts/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  kibot:
    uses: FEASTorg/bread-infra/.github/workflows/kibot-ci.yml@main

  gen-kibot-index:
    uses: FEASTorg/bread-infra/.github/workflows/publish-kibot.yml@main
    needs: [kibot]
    with:
      kibot_run_id: ${{ needs.kibot.outputs.kibot_run_id }}

  deploy-pages:
    uses: FEASTorg/bread-infra/.github/workflows/deploy-pages.yml@main
    needs: [gen-kibot-index]
    with:
      kibot_run_id: ${{ needs.kibot.outputs.kibot_run_id }}
      commit_sha: ${{ needs.gen-kibot-index.outputs.kibot_index_sha }}
